cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'hub'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'coreutils'
brew 'grc'
brew 'gettext'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'getantibody/tap/antibody'

cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
cask 'karabiner-elements'
