cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'ag'
brew 'autoenv'
brew 'coreutils'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'fasd'
brew 'fzf'
brew 'getantibody/tap/antibody'
brew 'gettext'
brew 'git'
brew 'grc'
brew 'hub'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'macvim', args: ['--with-override-system-vi']
brew 'node'
brew 'nvm'
brew 'openssl'
brew 'postgresql'
brew 'python3'
brew 'ranger'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'roundup'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'spark'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'watch'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'

cask '1password'
cask 'caffeine'
cask 'colorpicker-hex'
cask 'etcher'
cask 'firefoxdeveloperedition'
cask 'google-chrome'
cask 'handbrake'
cask 'iterm2'
cask 'karabiner-elements'
cask 'mounty'
cask 'postman'
cask 'skype'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
cask 'zoomus'
